version: '3.8'

services:
  stock_module:
    env_file:
      - "../.env"
    build:
      context: .
    container_name: stock_module
    restart: always
    ports:
      - "9084:8080"
    environment:
      MODULE_GROUP_ID: STOCK_GROUP_ID
      SERVICE_PORT: 9084
#    deploy:
#      mode: replicated
#      replicas: 2

